### ISSUE TITLE
[Request] - Power Ratio Sensor

### ISSUE THREAD

**Issue by Krzysztonek** [wil-lem/ha-hoymiles-s-cloud#3]
Hi @wil-lem

Just approaching you with one more kind request 🙏🏻 from my side ((hoping, the last one): please, consider creating one additional real-time sensor:
- `number.hoymiles_station_[solar_plant_name]_power_ratio`

This data is essential for recurrent solar plant efficiency comparison and analysis, and its value is available right from a user's dashboard on S-Miles Cloud.
It would prevent me from writing some statistical template sensors, which sometimes may cause some problems, leading to data inconsistency if their input comes from irregular external source. I know it rather should never happen, but I experienced such problems in the past using few other intergations.

I don't even dare to ask for too much because of your priceless time. You did a lot so far, I highly appreciate your work. However, if you find some spare time, please consider my kind request. 💟 I believe, it would be beneficial also for the others.

**Comment by wil-lem** [comment]
Hi @Krzysztonek , you can always ask :P But you're right, if it's available in the overview it should be somewhere in the cloud API, so I'll try to look for it. What would help me a lot is a screenshot from where you see it in the S-Miles Cloud interface so I can test it on my setup.

**Comment by Krzysztonek** [comment]
Hi, @wil-lem,

This is exactly, what I can see on my S-Miles Cloud Dashboard UI:

<img width="1119" height="558" alt="Image" src="https://github.com/user-attachments/assets/942d40c1-9e54-45bd-b0db-f77d0c777cf9" />

(EE production still not impressive, one more cloudy day in PL) 

In terms of microinverters' network connectivity status, you will find it here on `Devices` bookmark:

<img width="1572" height="691" alt="Image" src="https://github.com/user-attachments/assets/a263dfe2-fbc1-41c4-ad8a-5d0a9262599c" />

**Comment by Krzysztonek** [comment]
Curious, if you're progressing with these additional entities implementation (common `power_ratio` and individual `inverter_[number]_online`), @wil-lem.
Is there anything I could do more to support you?

**Comment by wil-lem** [comment]
Thanks @Krzysztonek , I added the power ratio for the entire station.
Just to be clear (though I'm not sure what's possible):
- You want to have an entity for each microinverter with a single sensor "online/offline"
- You also want to see power ratio per solar panel?
Hope you get some sunshine today :P

**Comment by Krzysztonek** [comment]
hi @wil-lem,

Seems I encountered a huge problem while trying to update this integration on my HA instance. 
Please have a look:

<img width="550" height="313" alt="Image" src="https://github.com/user-attachments/assets/d7d0d6cd-08a8-4efb-aaf9-4ec6830cb6e9" />

Is structure of this repo not compliant, indeed? Can you, please check? Otherwise I won't be able to update the integration and to use this new `power ratio` sensor..

When trying to reconfigure the existing integration, I'm getting this:

<img width="588" height="202" alt="Image" src="https://github.com/user-attachments/assets/69c748c4-dc6a-4a3c-a8a7-f643a9ba18ca" />



And answering your questions:

> * You want to have an entity for each microinverter with a single sensor "online/offline"

**YES:** This is exactly what would be really usefull. I would be able to control the connectivity status of each microinverter.

> * You also want to see power ratio per solar panel?

**NO:** Not necessary, let's be realistic and let's don't demand too much... 😃  If I have the `power ratio` sensor for my entire plant, it is more than enough! It will allow me to check the condition of my entire solar system and also to predict my daily generation.
This is how one of my panels looks on my HA dashboard:
<img width="101" height="71" alt="Image" src="https://github.com/user-attachments/assets/78cb043f-5a4c-4b33-992b-d809a80a9499" />

Its `individual power ratio` is shown on the up-right: `33.7%` in this case. It has been calculated in the fly as a division of two numeric values: nominal and momentary power of this single panel. 

> * Hope you get some sunshine today

**NO:** Still not a chance, unfortunately. Oct/Nov/Dec is the worst period in terms of sunshine in PL. Short days, clouds and fog.. As of New Year's Eve the weather usually gets much better here. So, waiting impatiently for sunny days... ;)

**Comment by wil-lem** [comment]
Ah I get it, I never made this to work with HACS. I updated the code, can you try again? I'm not sure what will happen with the old version of the integration. I hope it will just be overwritten.
No changes to the status of the inverters yet.

**Comment by Krzysztonek** [comment]
> I updated the code, can you try again?

Yes, now I was able to try again.
An update does NOT owerwrite the previous vestion It simply creates additional new entities instead. So, the configuration has been doubled.
To avoid discrepanties, I deleted all obsolete entities after update, keeping fresh entities only.

### What happened then?
Nothing. I can still see the same devices, same entities. No new entities appeared. `Power Ratio` sensor not found. Here is the list of *hoymiles* entities, excluding panels:

<img width="1211" height="435" alt="Image" src="https://github.com/user-attachments/assets/d6671128-da00-4dcc-800c-56a25663dbf5" />

Each solar panel creates 3 entities:
- `sensor.solar_plant_xxx_panel_current`
- `sensor.solar_plant_xxx_panel_voltage`
- `sensor.solar_plant_xxx_panel_power`

Nothing more, nothing less. 
Am I doing anything wrong? Or maybe a bug appered in the integration?

**Comment by wil-lem** [comment]
Hi, I could not find any specific issue that explains this but here's a few things that might work:
- First of all I didn't finish the HACS integration (old files were still around). I don't think this was an issue but it might cause the problem. There's a new version and it should be updatable through HACS

- Make sure that the custom components dir only contains the version installed by HACS, it should be called hoymiles_nimbus and the manifest.json should look like this:

<img width="1003" height="339" alt="Image" src="https://github.com/user-attachments/assets/e9913669-a3ca-4659-86e5-bffc85701fdb" />

If there's other dirs starting with hoymiles they might be an old version of this integration.

- I added logging to see what's happening, if you download the new versiosn, restart and wait a while and search the logs for "nimbus" it should look something like this:

<img width="915" height="825" alt="Image" src="https://github.com/user-attachments/assets/bbc36e4d-33c9-4702-8914-8bb3fd0407d0" />

- If  you enable debug logging you can see even more

<img width="1319" height="323" alt="Image" src="https://github.com/user-attachments/assets/3a13b113-65c1-4156-8ac7-575387680d5f" />
(make sure to look at raw logs)

Can you look for errors in the logs so we can pinpoint where a request might go wrong.

I hope we can find what's going on this way, sorry it's not an easy fix this time 😉
